name: ponysay
version: '3.0.3'
summary: cowsay reimplemention for ponies
description: |
  Ponysay displays an image of a My Little Pony pony saying a message provided 
  by the user in a terminal, or a quote from the show My Little Pony: 
  Friendship is Magic (MLP:FiM). 
  Historically ponysay was a wrapper for cowsay, but has since version 2.1 
  become an independent reimplementation of cowsay.

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

apps:
  ponysay:
    command: ./bin/ponysay
    environment:
      LANG: C.UTF-8
  ponythink:
    command: ./bin/ponythink
    environment:
      LANG: C.UTF-8

parts:
  ponysay:
    source: https://github.com/erkin/ponysay.git
    source-tag: 3.0.3
    plugin: dump
#    build-attributes:
#    - no-system-libraries
    stage-packages:
    - python3
    - coreutils
    build-packages:
    - gzip
    - texinfo
    override-pull: |
      craftctl default
      sed -i -n '1h; 1!H; ${ g; s/ For an extensive.* than described here.//p }' $CRAFT_PART_SRC/src/__main__.py
      sed -i "s|encode('utf-8')|encode('utf-8', errors='surrogateescape')|g" $CRAFT_PART_SRC/src/common.py
      sed -i "s|is not ','|!= ','|g" $CRAFT_PART_SRC/src/backend.py
      sed -i 's|/usr/share/ponysay/|$SNAP/share/ponysay/|g' $CRAFT_PART_SRC/src/ponysay.py
      sed -i 's|/etc/|$SNAP_DATA/etc/|g' $CRAFT_PART_SRC/src/ponysay.py
      sed -i 's|/var/cache/ponysay|$HOME/.cache/ponysay|g' $CRAFT_PART_SRC/src/kms.py
    override-build: |
      craftctl default
      ./setup.py --freedom=partial --prefix=$CRAFT_PART_INSTALL --without-shared-cache --without-pdf --without-ponysay-tool install
    prime: [ -balloons, -completion, -dev, -extraponies, -extras, -extrattyponies,
        -manuals, -ponies, -ponyquotes, -share/ucsmap, -src, -ttyponies, -dependency-test.sh, -ponysay.pdf, -setup.py ]
